import { Injectable, signal } from '@angular/core';
import { Company, Contact, Opportunity, Task, Activity, User, EmailTemplate, AutoActivity, ImportableEntity, RelatedEntity, Project, Product, Lead, Quote, Case } from '../models/crm.models';

export interface ContactPopoverData {
  companyId: string;
  position: { x: number; y: number };
}

@Injectable({
  providedIn: 'root',
})
export class ModalService {
  // Header state
  isProfileMenuOpen = signal(false);
  isNotificationCenterOpen = signal(false);

  // Profile modal state
  isProfileModalOpen = signal(false);

  // Fix: Use `undefined` to represent a closed/uninitialized state for entity modals. `null` will represent creating a new entity.
  // Modal states for CRUD operations
  selectedCompany = signal<Company | null | undefined>(undefined);
  selectedContact = signal<Contact | null | undefined>(undefined);
  selectedOpportunity = signal<Opportunity | null | undefined>(undefined);
  selectedProject = signal<Project | null | undefined>(undefined);
  selectedProduct = signal<Product | null | undefined>(undefined);
  editingTask = signal<Partial<Task> | null | undefined>(undefined);
  editingActivity = signal<Activity | null | undefined>(undefined);
  autoGeneratedActivity = signal<AutoActivity | null>(null);
  editingUser = signal<User | null | undefined>(undefined);
  editingTemplate = signal<EmailTemplate | null | undefined>(undefined);
  previewingTemplate = signal<EmailTemplate | undefined>(undefined);
  selectedLead = signal<Lead | null | undefined>(undefined);
  leadToConvert = signal<Lead | null>(null);
  selectedQuote = signal<Quote | null | undefined>(undefined);
  previewingQuote = signal<Quote | undefined>(undefined);
  selectedCase = signal<Case | null | undefined>(undefined);
  isModalReadonly = signal(false);
  
  // Email Composer
  emailComposerData = signal<{ to: string; subject: string; body: string; relatedEntity: RelatedEntity | null }>({ to: '', subject: '', body: '', relatedEntity: null });

  // Import Modal state
  isImportModalOpen = signal(false);
  importTarget = signal<ImportableEntity | null>(null);
  importStep = signal<'upload' | 'map'>('upload');
  csvHeaders = signal<string[]>([]);
  csvData = signal<{[key: string]: string}[]>([]);
  fieldMappings = signal<{[key: string]: string}>({});
  
  // Contact Popover state
  contactPopoverData = signal<ContactPopoverData | null>(null);

  // Upgrade Modal State
  isUpgradeModalOpen = signal<{ open: boolean, reason: string }>({ open: false, reason: '' });

  // --- Modal Management ---
  openProfileModal() {
    this.isProfileModalOpen.set(true);
    this.isProfileMenuOpen.set(false);
  }

  closeProfileModal() {
    this.isProfileModalOpen.set(false);
  }
  
  openCompanyDetails(company: Company | null) { this.selectedCompany.set(company); }
  closeCompanyDetails() { this.selectedCompany.set(undefined); }

  openContactModal(contact: Contact | null) { this.selectedContact.set(contact); }
  closeContactModal() { this.selectedContact.set(undefined); }

  openOpportunityModal(opp: Opportunity | null) { this.selectedOpportunity.set(opp); }
  closeOpportunityModal() { this.selectedOpportunity.set(undefined); }
  
  openTaskModal(task: Partial<Task> | null) { this.editingTask.set(task); }
  closeTaskModal() {
    this.editingTask.set(undefined);
    this.isModalReadonly.set(false);
  }
  
  openProjectModal(project: Project | null) { this.selectedProject.set(project); }
  closeProjectModal() { this.selectedProject.set(undefined); }

  openProductModal(product: Product | null) { this.selectedProduct.set(product); }
  closeProductModal() { this.selectedProduct.set(undefined); }

  openActivityEditModal(activity: Activity | null) { this.editingActivity.set(activity); }
  closeActivityEditModal() {
    this.editingActivity.set(undefined);
    this.isModalReadonly.set(false);
  }

  openUserModal(user: User | null) { this.editingUser.set(user); }
  closeUserModal() { this.editingUser.set(undefined); }

  openTemplateEditor(template: EmailTemplate | null) { this.editingTemplate.set(template); }
  closeTemplateEditor() { this.editingTemplate.set(undefined); }

  openTemplatePreview(template: EmailTemplate) { this.previewingTemplate.set(template); }
  closeTemplatePreview() { this.previewingTemplate.set(undefined); }

  openLeadModal(lead: Lead | null) { this.selectedLead.set(lead); }
  closeLeadModal() { this.selectedLead.set(undefined); }

  openLeadConversionModal(lead: Lead) { this.leadToConvert.set(lead); }
  closeLeadConversionModal() { this.leadToConvert.set(null); }

  openQuoteModal(quote: Quote | null) { this.selectedQuote.set(quote); }
  closeQuoteModal() { this.selectedQuote.set(undefined); }
  
  openQuotePreview(quote: Quote) { this.previewingQuote.set(quote); }
  closeQuotePreview() { this.previewingQuote.set(undefined); }

  openCaseModal(kase: Case | null) { this.selectedCase.set(kase); }
  closeCaseModal() { this.selectedCase.set(undefined); }
  
  openEmailComposer(data: { to: string; subject: string; body: string; relatedEntity: RelatedEntity | null }) { this.emailComposerData.set(data); }
  closeEmailComposer() { this.emailComposerData.set({ to: '', subject: '', body: '', relatedEntity: null }); }

  openImportModal(target: ImportableEntity) {
    this.importTarget.set(target);
    this.isImportModalOpen.set(true);
    this.importStep.set('upload');
    this.csvData.set([]);
    this.csvHeaders.set([]);
    this.fieldMappings.set({});
  }

  closeImportModal() {
    this.isImportModalOpen.set(false);
    this.importTarget.set(null);
  }

  // --- Upgrade Modal ---
  openUpgradeModal(reason: string) { this.isUpgradeModalOpen.set({ open: true, reason }); }
  closeUpgradeModal() { this.isUpgradeModalOpen.set({ open: false, reason: '' }); }

  // --- Contact Popover ---
  openContactPopover(data: ContactPopoverData) { this.contactPopoverData.set(data); }
  closeContactPopover() { this.contactPopoverData.set(null); }
}
