import { Injectable, signal, computed, effect } from '@angular/core';
import { ColorPalette, Themes } from '../models/theme.models';

@Injectable({
  providedIn: 'root',
})
export class ThemeService {
  readonly themes: Themes = {
    'dashboard-ui': {
      // Backgrounds
      'bg-base': 'bg-slate-100',
      'bg-primary': 'bg-white',
      'bg-primary-hover': 'hover:bg-slate-50',
      'bg-primary-hover-subtle': 'hover:bg-slate-50/50',
      'bg-secondary': 'bg-slate-100',
      'bg-secondary-hover': 'hover:bg-slate-200',
      'bg-tertiary': 'bg-white',
      'bg-contrast': 'bg-slate-900',
      'bg-inverted': 'bg-slate-800',
      'bg-disabled': 'bg-slate-400',
      'bg-transparent': 'bg-transparent',
      'bg-transparent-hover': 'hover:bg-black/5',

      // Texts
      'text-base': 'text-slate-600',
      'text-primary': 'text-slate-800',
      'text-secondary': 'text-slate-500',
      'text-tertiary': 'text-slate-400',
      'text-inverted': 'text-white',
      'text-contrast': 'text-slate-800',
      'text-contrast-secondary': 'text-slate-300',
      'text-contrast-tertiary': 'text-slate-400',
      'placeholder-text': 'placeholder:text-slate-400',

      // Borders
      'border-primary': 'border-slate-200',
      'border-secondary': 'border-slate-300',
      'border-contrast': 'border-slate-700',

      // Accent Colors
      'bg-accent': 'bg-sky-500',
      'hover:bg-accent-hover': 'hover:bg-sky-600',
      'text-accent': 'text-sky-600',
      'hover:text-accent-hover': 'hover:text-sky-700',
      'border-accent': 'border-sky-500',
      'focus:ring-accent': 'focus:ring-sky-500',
      'focus:border-accent': 'focus:border-sky-500',
      'focus:ring-accent-subtle': 'focus:ring-sky-500/50',
      'bg-accent-subtle': 'bg-sky-500/10',
      'hover:bg-accent-subtle-hover': 'hover:bg-sky-500/20',
      'text-accent-subtle': 'text-sky-700',
      'ring-accent': 'ring-sky-500',
      
      // Other UI Colors
      'text-danger': 'text-red-600',
      'hover:text-danger-hover': 'hover:text-red-700',
      'bg-danger-subtle': 'bg-red-500/10',
      'hover:bg-danger-subtle-hover': 'hover:bg-red-500/20',
      'border-danger-subtle': 'border-red-500/20',
      'text-success': 'text-emerald-600',
      'bg-success-subtle': 'bg-emerald-500/10',
      'text-warning': 'text-amber-600',
      'bg-warning-subtle': 'bg-amber-500/10',
      'border-warning-subtle': 'border-amber-500/20',
      'text-info': 'text-sky-600',
      'bg-info-subtle': 'bg-sky-500/10',
      'text-special': 'text-violet-600',
      'bg-special-subtle': 'bg-violet-500/10',
      'ring-base-for-notifications': 'ring-white',
      'gradient-from-primary': 'from-white',
      'text-on-accent': 'text-white',
    },
    'midone-light': {
      // Backgrounds
      'bg-base': 'bg-slate-100',
      'bg-primary': 'bg-white',
      'bg-primary-hover': 'hover:bg-slate-50',
      'bg-primary-hover-subtle': 'hover:bg-slate-50/50',
      'bg-secondary': 'bg-slate-200',
      'bg-secondary-hover': 'hover:bg-slate-300',
      'bg-tertiary': 'bg-blue-800',
      'bg-contrast': 'bg-slate-900',
      'bg-inverted': 'bg-slate-800',
      'bg-disabled': 'bg-slate-300',
      'bg-transparent': 'bg-transparent',
      'bg-transparent-hover': 'hover:bg-black/5',

      // Texts
      'text-base': 'text-slate-600',
      'text-primary': 'text-slate-800',
      'text-secondary': 'text-slate-500',
      'text-tertiary': 'text-slate-400',
      'text-inverted': 'text-white',
      'text-contrast': 'text-white',
      'text-contrast-secondary': 'text-slate-300',
      'text-contrast-tertiary': 'text-slate-400',
      'placeholder-text': 'placeholder:text-slate-400',

      // Borders
      'border-primary': 'border-slate-200',
      'border-secondary': 'border-slate-300',
      'border-contrast': 'border-slate-700',

      // Accent Colors
      'bg-accent': 'bg-blue-600',
      'hover:bg-accent-hover': 'hover:bg-blue-700',
      'text-accent': 'text-blue-600',
      'hover:text-accent-hover': 'hover:text-blue-700',
      'border-accent': 'border-blue-500',
      'focus:ring-accent': 'focus:ring-blue-500',
      'focus:border-accent': 'focus:border-blue-500',
      'focus:ring-accent-subtle': 'focus:ring-blue-500/50',
      'bg-accent-subtle': 'bg-blue-500/10',
      'hover:bg-accent-subtle-hover': 'hover:bg-blue-500/20',
      'text-accent-subtle': 'text-blue-700',
      'ring-accent': 'ring-blue-500',
      
      // Other UI Colors
      'text-danger': 'text-red-600',
      'hover:text-danger-hover': 'hover:text-red-700',
      'bg-danger-subtle': 'bg-red-500/10',
      'hover:bg-danger-subtle-hover': 'hover:bg-red-500/20',
      'border-danger-subtle': 'border-red-500/20',
      'text-success': 'text-emerald-600',
      'bg-success-subtle': 'bg-emerald-500/10',
      'text-warning': 'text-amber-600',
      'bg-warning-subtle': 'bg-amber-500/10',
      'border-warning-subtle': 'border-amber-500/20',
      'text-info': 'text-sky-600',
      'bg-info-subtle': 'bg-sky-500/10',
      'text-special': 'text-violet-600',
      'bg-special-subtle': 'bg-violet-500/10',
      'ring-base-for-notifications': 'ring-white',
      'gradient-from-primary': 'from-white',
      'text-on-accent': 'text-white',
    },
    'glassy-blue': {
      'bg-base': 'bg-sky-50',
      'bg-primary': 'bg-white',
      'bg-primary-hover': 'hover:bg-sky-100/50',
      'bg-primary-hover-subtle': 'hover:bg-sky-100/70',
      'bg-secondary': 'bg-sky-100',
      'bg-secondary-hover': 'hover:bg-sky-200',
      'bg-tertiary': 'bg-sky-700',
      'bg-contrast': 'bg-slate-900',
      'bg-inverted': 'bg-slate-800',
      'bg-disabled': 'bg-slate-300',
      'bg-transparent': 'bg-transparent',
      'bg-transparent-hover': 'hover:bg-black/5',
      'text-base': 'text-slate-600',
      'text-primary': 'text-slate-800',
      'text-secondary': 'text-slate-500',
      'text-tertiary': 'text-slate-400',
      'text-inverted': 'text-white',
      'text-contrast': 'text-white',
      'text-contrast-secondary': 'text-slate-300',
      'text-contrast-tertiary': 'text-slate-400',
      'placeholder-text': 'placeholder:text-slate-400',
      'border-primary': 'border-sky-100',
      'border-secondary': 'border-sky-200',
      'border-contrast': 'border-slate-700',
      'bg-accent': 'bg-sky-500',
      'hover:bg-accent-hover': 'hover:bg-sky-600',
      'text-accent': 'text-sky-600',
      'hover:text-accent-hover': 'hover:text-sky-700',
      'border-accent': 'border-sky-500',
      'focus:ring-accent': 'focus:ring-sky-500',
      'focus:border-accent': 'focus:border-sky-500',
      'focus:ring-accent-subtle': 'focus:ring-sky-500/50',
      'bg-accent-subtle': 'bg-sky-500/10',
      'hover:bg-accent-subtle-hover': 'hover:bg-sky-500/20',
      'text-accent-subtle': 'text-sky-700',
      'ring-accent': 'ring-sky-500',
      'text-danger': 'text-red-600',
      'hover:text-danger-hover': 'hover:text-red-700',
      'bg-danger-subtle': 'bg-red-500/10',
      'hover:bg-danger-subtle-hover': 'hover:bg-red-500/20',
      'border-danger-subtle': 'border-red-500/20',
      'text-success': 'text-emerald-600',
      'bg-success-subtle': 'bg-emerald-500/10',
      'text-warning': 'text-amber-600',
      'bg-warning-subtle': 'bg-amber-500/10',
      'border-warning-subtle': 'border-amber-500/20',
      'text-info': 'text-sky-600',
      'bg-info-subtle': 'bg-sky-500/10',
      'text-special': 'text-violet-600',
      'bg-special-subtle': 'bg-violet-500/10',
      'ring-base-for-notifications': 'ring-white',
      'gradient-from-primary': 'from-white',
      'text-on-accent': 'text-white',
    },
    'sangu-light': {
      'bg-base': 'bg-blue-50',
      'bg-primary': 'bg-white',
      'bg-primary-hover': 'hover:bg-blue-100/50',
      'bg-primary-hover-subtle': 'hover:bg-blue-100/70',
      'bg-secondary': 'bg-blue-100',
      'bg-secondary-hover': 'hover:bg-blue-200',
      'bg-tertiary': 'bg-blue-700',
      'bg-contrast': 'bg-slate-900',
      'bg-inverted': 'bg-slate-800',
      'bg-disabled': 'bg-slate-300',
      'bg-transparent': 'bg-transparent',
      'bg-transparent-hover': 'hover:bg-black/5',
      'text-base': 'text-slate-600',
      'text-primary': 'text-slate-800',
      'text-secondary': 'text-slate-500',
      'text-tertiary': 'text-slate-400',
      'text-inverted': 'text-white',
      'text-contrast': 'text-white',
      'text-contrast-secondary': 'text-slate-300',
      'text-contrast-tertiary': 'text-slate-400',
      'placeholder-text': 'placeholder:text-slate-400',
      'border-primary': 'border-blue-100',
      'border-secondary': 'border-blue-200',
      'border-contrast': 'border-slate-700',
      'bg-accent': 'bg-blue-500',
      'hover:bg-accent-hover': 'hover:bg-blue-600',
      'text-accent': 'text-blue-600',
      'hover:text-accent-hover': 'hover:text-blue-700',
      'border-accent': 'border-blue-500',
      'focus:ring-accent': 'focus:ring-blue-500',
      'focus:border-accent': 'focus:border-blue-500',
      'focus:ring-accent-subtle': 'focus:ring-blue-500/50',
      'bg-accent-subtle': 'bg-blue-500/10',
      'hover:bg-accent-subtle-hover': 'hover:bg-blue-500/20',
      'text-accent-subtle': 'text-blue-700',
      'ring-accent': 'ring-blue-500',
      'text-danger': 'text-red-600',
      'hover:text-danger-hover': 'hover:text-red-700',
      'bg-danger-subtle': 'bg-red-500/10',
      'hover:bg-danger-subtle-hover': 'hover:bg-red-500/20',
      'border-danger-subtle': 'border-red-500/20',
      'text-success': 'text-emerald-600',
      'bg-success-subtle': 'bg-emerald-500/10',
      'text-warning': 'text-amber-600',
      'bg-warning-subtle': 'bg-amber-500/10',
      'border-warning-subtle': 'border-amber-500/20',
      'text-info': 'text-sky-600',
      'bg-info-subtle': 'bg-sky-500/10',
      'text-special': 'text-violet-600',
      'bg-special-subtle': 'bg-violet-500/10',
      'ring-base-for-notifications': 'ring-white',
      'gradient-from-primary': 'from-white',
      'text-on-accent': 'text-white',
    },
    'lilac-breeze': {
      'bg-base': 'bg-violet-50',
      'bg-primary': 'bg-white',
      'bg-primary-hover': 'hover:bg-violet-100/50',
      'bg-primary-hover-subtle': 'hover:bg-violet-100/70',
      'bg-secondary': 'bg-violet-100',
      'bg-secondary-hover': 'hover:bg-violet-200',
      'bg-tertiary': 'bg-violet-700',
      'bg-contrast': 'bg-slate-900',
      'bg-inverted': 'bg-slate-800',
      'bg-disabled': 'bg-slate-300',
      'bg-transparent': 'bg-transparent',
      'bg-transparent-hover': 'hover:bg-black/5',
      'text-base': 'text-slate-600',
      'text-primary': 'text-slate-800',
      'text-secondary': 'text-slate-500',
      'text-tertiary': 'text-slate-400',
      'text-inverted': 'text-white',
      'text-contrast': 'text-white',
      'text-contrast-secondary': 'text-slate-300',
      'text-contrast-tertiary': 'text-slate-400',
      'placeholder-text': 'placeholder:text-slate-400',
      'border-primary': 'border-violet-100',
      'border-secondary': 'border-violet-200',
      'border-contrast': 'border-slate-700',
      'bg-accent': 'bg-violet-500',
      'hover:bg-accent-hover': 'hover:bg-violet-600',
      'text-accent': 'text-violet-600',
      'hover:text-accent-hover': 'hover:text-violet-700',
      'border-accent': 'border-violet-500',
      'focus:ring-accent': 'focus:ring-violet-500',
      'focus:border-accent': 'focus:border-violet-500',
      'focus:ring-accent-subtle': 'focus:ring-violet-500/50',
      'bg-accent-subtle': 'bg-violet-500/10',
      'hover:bg-accent-subtle-hover': 'hover:bg-violet-500/20',
      'text-accent-subtle': 'text-violet-700',
      'ring-accent': 'ring-violet-500',
      'text-danger': 'text-red-600',
      'hover:text-danger-hover': 'hover:text-red-700',
      'bg-danger-subtle': 'bg-red-500/10',
      'hover:bg-danger-subtle-hover': 'hover:bg-red-500/20',
      'border-danger-subtle': 'border-red-500/20',
      'text-success': 'text-emerald-600',
      'bg-success-subtle': 'bg-emerald-500/10',
      'text-warning': 'text-amber-600',
      'bg-warning-subtle': 'bg-amber-500/10',
      'border-warning-subtle': 'border-amber-500/20',
      'text-info': 'text-sky-600',
      'bg-info-subtle': 'bg-sky-500/10',
      'text-special': 'text-violet-600',
      'bg-special-subtle': 'bg-violet-500/10',
      'ring-base-for-notifications': 'ring-white',
      'gradient-from-primary': 'from-white',
      'text-on-accent': 'text-white',
    },
    'charcoal-ember': {
      'bg-base': 'bg-gray-900', 'bg-primary': 'bg-gray-800', 'bg-primary-hover': 'hover:bg-gray-700', 'bg-primary-hover-subtle': 'hover:bg-gray-700/50', 'bg-secondary': 'bg-gray-700', 'bg-secondary-hover': 'hover:bg-gray-600', 'bg-tertiary': 'bg-black', 'bg-contrast': 'bg-white', 'bg-inverted': 'bg-gray-100', 'bg-disabled': 'bg-gray-600', 'bg-transparent': 'bg-transparent', 'bg-transparent-hover': 'hover:bg-white/10',
      'text-base': 'text-gray-300', 'text-primary': 'text-white', 'text-secondary': 'text-gray-400', 'text-tertiary': 'text-gray-500', 'text-inverted': 'text-gray-900', 'text-contrast': 'text-white', 'text-contrast-secondary': 'text-gray-500', 'text-contrast-tertiary': 'text-gray-400', 'placeholder-text': 'placeholder:text-gray-500',
      'border-primary': 'border-gray-700', 'border-secondary': 'border-gray-600', 'border-contrast': 'border-gray-200',
      'bg-accent': 'bg-red-600', 'hover:bg-accent-hover': 'hover:bg-red-700', 'text-accent': 'text-red-500', 'hover:text-accent-hover': 'hover:text-red-400', 'border-accent': 'border-red-500', 'focus:ring-accent': 'focus:ring-red-500', 'focus:border-accent': 'focus:border-red-500', 'focus:ring-accent-subtle': 'focus:ring-red-500/50', 'bg-accent-subtle': 'bg-red-500/10', 'hover:bg-accent-subtle-hover': 'hover:bg-red-500/20', 'text-accent-subtle': 'text-red-300', 'ring-accent': 'ring-red-500',
      'text-danger': 'text-red-400', 'hover:text-danger-hover': 'hover:text-red-300', 'bg-danger-subtle': 'bg-red-500/10', 'hover:bg-danger-subtle-hover': 'hover:bg-red-500/20', 'border-danger-subtle': 'border-red-500/30', 'text-success': 'text-emerald-400', 'bg-success-subtle': 'bg-emerald-500/10', 'text-warning': 'text-yellow-400', 'bg-warning-subtle': 'bg-yellow-400/10', 'border-warning-subtle': 'border-yellow-400/20', 'text-info': 'text-sky-300', 'bg-info-subtle': 'bg-sky-500/10', 'text-special': 'text-violet-300', 'bg-special-subtle': 'bg-violet-500/10',
      'ring-base-for-notifications': 'ring-gray-800', 'gradient-from-primary': 'from-gray-800', 'text-on-accent': 'text-white',
    },
    'midnight-glow': {
      'bg-base': 'bg-slate-900', 'bg-primary': 'bg-slate-800', 'bg-primary-hover': 'hover:bg-slate-700', 'bg-primary-hover-subtle': 'hover:bg-slate-700/50', 'bg-secondary': 'bg-slate-700', 'bg-secondary-hover': 'hover:bg-slate-600', 'bg-tertiary': 'bg-black', 'bg-contrast': 'bg-white', 'bg-inverted': 'bg-slate-100', 'bg-disabled': 'bg-slate-600', 'bg-transparent': 'bg-transparent', 'bg-transparent-hover': 'hover:bg-white/10',
      'text-base': 'text-slate-300', 'text-primary': 'text-white', 'text-secondary': 'text-slate-400', 'text-tertiary': 'text-slate-500', 'text-inverted': 'text-slate-900', 'text-contrast': 'text-white', 'text-contrast-secondary': 'text-slate-500', 'text-contrast-tertiary': 'text-slate-400', 'placeholder-text': 'placeholder:text-gray-500',
      'border-primary': 'border-slate-700', 'border-secondary': 'border-slate-600', 'border-contrast': 'border-slate-200',
      'bg-accent': 'bg-purple-600', 'hover:bg-accent-hover': 'hover:bg-purple-700', 'text-accent': 'text-purple-400', 'hover:text-accent-hover': 'hover:text-purple-300', 'border-accent': 'border-purple-500', 'focus:ring-accent': 'focus:ring-purple-500', 'focus:border-accent': 'focus:border-purple-500', 'focus:ring-accent-subtle': 'focus:ring-purple-500/50', 'bg-accent-subtle': 'bg-purple-500/10', 'hover:bg-accent-subtle-hover': 'hover:bg-purple-500/20', 'text-accent-subtle': 'text-purple-300', 'ring-accent': 'ring-purple-500',
      'text-danger': 'text-red-400', 'hover:text-danger-hover': 'hover:text-red-300', 'bg-danger-subtle': 'bg-red-500/10', 'hover:bg-danger-subtle-hover': 'hover:bg-red-500/20', 'border-danger-subtle': 'border-red-500/30', 'text-success': 'text-green-400', 'bg-success-subtle': 'bg-green-500/10', 'text-warning': 'text-yellow-400', 'bg-warning-subtle': 'bg-yellow-500/10', 'border-warning-subtle': 'border-yellow-400/20', 'text-info': 'text-sky-300', 'bg-info-subtle': 'bg-sky-500/10', 'text-special': 'text-violet-300', 'bg-special-subtle': 'bg-violet-500/10',
      'ring-base-for-notifications': 'ring-slate-800', 'gradient-from-primary': 'from-slate-800', 'text-on-accent': 'text-white',
    }
  };

  availableThemes = computed(() => Object.keys(this.themes));
  currentThemeName = signal<string>('dashboard-ui');

  constructor() {
    const storedTheme = localStorage.getItem('crm-theme');
    if (storedTheme && this.themes[storedTheme]) {
      this.currentThemeName.set(storedTheme);
    }

    effect(() => {
      localStorage.setItem('crm-theme', this.currentThemeName());
    });
  }

  setTheme(themeName: string) {
    if (this.themes[themeName]) {
      this.currentThemeName.set(themeName);
    }
  }

  palette = computed<ColorPalette>(() => this.themes[this.currentThemeName()]);

  c(key: keyof ColorPalette): string {
    return this.palette()[key] ?? '';
  }
}
