import { Injectable, inject } from '@angular/core';
import { ModalService, ContactPopoverData } from './modal.service';
import { ViewService } from './view.service';
import { TableService } from './table.service';
import { Company, Contact, Opportunity, Task, Activity, User, EmailTemplate, AutoActivity, ImportableEntity, RelatedEntity, Project, Product, Lead, Quote, Case } from '../models/crm.models';

@Injectable({
  providedIn: 'root'
})
export class UiService {
  private modalService = inject(ModalService);
  private viewService = inject(ViewService);
  private tableService = inject(TableService);

  // --- From ModalService ---
  isProfileMenuOpen = this.modalService.isProfileMenuOpen;
  isNotificationCenterOpen = this.modalService.isNotificationCenterOpen;
  isProfileModalOpen = this.modalService.isProfileModalOpen;
  selectedCompany = this.modalService.selectedCompany;
  selectedContact = this.modalService.selectedContact;
  selectedOpportunity = this.modalService.selectedOpportunity;
  selectedProject = this.modalService.selectedProject;
  selectedProduct = this.modalService.selectedProduct;
  editingTask = this.modalService.editingTask;
  editingActivity = this.modalService.editingActivity;
  autoGeneratedActivity = this.modalService.autoGeneratedActivity;
  editingUser = this.modalService.editingUser;
  editingTemplate = this.modalService.editingTemplate;
  previewingTemplate = this.modalService.previewingTemplate;
  selectedLead = this.modalService.selectedLead;
  leadToConvert = this.modalService.leadToConvert;
  selectedQuote = this.modalService.selectedQuote;
  previewingQuote = this.modalService.previewingQuote;
  selectedCase = this.modalService.selectedCase;
  isModalReadonly = this.modalService.isModalReadonly;
  emailComposerData = this.modalService.emailComposerData;
  isImportModalOpen = this.modalService.isImportModalOpen;
  importTarget = this.modalService.importTarget;
  importStep = this.modalService.importStep;
  csvHeaders = this.modalService.csvHeaders;
  csvData = this.modalService.csvData;
  fieldMappings = this.modalService.fieldMappings;
  contactPopoverData = this.modalService.contactPopoverData;
  isUpgradeModalOpen = this.modalService.isUpgradeModalOpen;

  openProfileModal = () => this.modalService.openProfileModal();
  closeProfileModal = () => this.modalService.closeProfileModal();
  openCompanyDetails = (company: Company | null) => this.modalService.openCompanyDetails(company);
  closeCompanyDetails = () => this.modalService.closeCompanyDetails();
  openContactModal = (contact: Contact | null) => this.modalService.openContactModal(contact);
  closeContactModal = () => this.modalService.closeContactModal();
  openOpportunityModal = (opp: Opportunity | null) => this.modalService.openOpportunityModal(opp);
  closeOpportunityModal = () => this.modalService.closeOpportunityModal();
  openTaskModal = (task: Partial<Task> | null) => this.modalService.openTaskModal(task);
  closeTaskModal = () => this.modalService.closeTaskModal();
  openProjectModal = (project: Project | null) => this.modalService.openProjectModal(project);
  closeProjectModal = () => this.modalService.closeProjectModal();
  openProductModal = (product: Product | null) => this.modalService.openProductModal(product);
  closeProductModal = () => this.modalService.closeProductModal();
  openActivityEditModal = (activity: Activity | null) => this.modalService.openActivityEditModal(activity);
  closeActivityEditModal = () => this.modalService.closeActivityEditModal();
  openUserModal = (user: User | null) => this.modalService.openUserModal(user);
  closeUserModal = () => this.modalService.closeUserModal();
  openTemplateEditor = (template: EmailTemplate | null) => this.modalService.openTemplateEditor(template);
  closeTemplateEditor = () => this.modalService.closeTemplateEditor();
  openTemplatePreview = (template: EmailTemplate) => this.modalService.openTemplatePreview(template);
  closeTemplatePreview = () => this.modalService.closeTemplatePreview();
  openLeadModal = (lead: Lead | null) => this.modalService.openLeadModal(lead);
  closeLeadModal = () => this.modalService.closeLeadModal();
  openLeadConversionModal = (lead: Lead) => this.modalService.openLeadConversionModal(lead);
  closeLeadConversionModal = () => this.modalService.closeLeadConversionModal();
  openQuoteModal = (quote: Quote | null) => this.modalService.openQuoteModal(quote);
  closeQuoteModal = () => this.modalService.closeQuoteModal();
  openQuotePreview = (quote: Quote) => this.modalService.openQuotePreview(quote);
  closeQuotePreview = () => this.modalService.closeQuotePreview();
  openCaseModal = (kase: Case | null) => this.modalService.openCaseModal(kase);
  closeCaseModal = () => this.modalService.closeCaseModal();
  openEmailComposer = (data: { to: string; subject: string; body: string; relatedEntity: RelatedEntity | null }) => this.modalService.openEmailComposer(data);
  closeEmailComposer = () => this.modalService.closeEmailComposer();
  openImportModal = (target: ImportableEntity) => this.modalService.openImportModal(target);
  closeImportModal = () => this.modalService.closeImportModal();
  openUpgradeModal = (reason: string) => this.modalService.openUpgradeModal(reason);
  closeUpgradeModal = () => this.modalService.closeUpgradeModal();
  openContactPopover = (data: ContactPopoverData) => this.modalService.openContactPopover(data);
  closeContactPopover = () => this.modalService.closeContactPopover();
  
  // --- From ViewService ---
  profileView = this.viewService.profileView;

  // --- From TableService ---
  activeColumnCustomization = this.tableService.activeColumnCustomization;
  tableColumnConfigs = this.tableService.tableColumnConfigs;
  pagination = this.tableService.pagination;
  setItemsPerPage = (count: number) => this.tableService.setItemsPerPage(count);
  setCurrentPage = (table: any, page: number) => this.tableService.setCurrentPage(table, page);
}
