import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthService } from './app/services/auth.service';
import { UiService } from './app/services/ui.service';

// Layout components
import { HeaderComponent } from './app/layout/header/header.component';
import { SidebarComponent } from './app/layout/sidebar/sidebar.component';

// Page components
import { DashboardComponent } from './app/components/dashboard/dashboard.component';
import { CompaniesComponent } from './app/components/companies/companies.component';
import { ContactsComponent } from './app/components/contacts/contacts.component';
import { OpportunitiesComponent } from './app/components/opportunities/opportunities.component';
import { TasksComponent } from './app/components/tasks/tasks.component';
import { ActivitiesComponent } from './app/components/activities/activities.component';
import { UsersRolesComponent } from './app/components/users-roles/users-roles.component';
import { EmailTemplatesComponent } from './app/components/email-templates/email-templates.component';
import { AuditLogComponent } from './app/components/audit-log/audit-log.component';

// Auth component
import { AuthComponent } from './app/components/auth/auth.component';

// Modal components
import { ProfileModalComponent } from './app/components/modals/profile-modal/profile-modal.component';
import { CompanyModalComponent } from './app/components/modals/company-modal/company-modal.component';
import { ContactModalComponent } from './app/components/modals/contact-modal/contact-modal.component';
import { OpportunityModalComponent } from './app/components/modals/opportunity-modal/opportunity-modal.component';
import { TaskModalComponent } from './app/components/modals/task-modal/task-modal.component';
import { ActivityModalComponent } from './app/components/modals/activity-modal/activity-modal.component';
import { UserModalComponent } from './app/components/modals/user-modal/user-modal.component';
import { EmailTemplateModalComponent } from './app/components/modals/email-template-modal/email-template-modal.component';
import { EmailComposerModalComponent } from './app/components/modals/email-composer-modal/email-composer-modal.component';
import { ImportModalComponent } from './app/components/modals/import-modal/import-modal.component';
import { ColumnCustomizationComponent } from './app/components/modals/column-customization/column-customization.component';
import { EmailTemplatePreviewModalComponent } from './app/components/modals/email-template-preview-modal/email-template-preview-modal.component';

@Component({
  selector: 'app-root',
  template: `
    @if (authService.isAuthenticated()) {
      <div class="flex h-screen bg-gray-900">
        <app-sidebar></app-sidebar>
        <div class="flex-1 flex flex-col overflow-hidden">
          <app-header></app-header>
          <main class="flex-1 overflow-x-hidden overflow-y-auto p-4 sm:p-6">
            @switch (uiService.view()) {
              @case ('dashboard') { <app-dashboard /> }
              @case ('companies') { <app-companies /> }
              @case ('contacts') { <app-contacts /> }
              @case ('opportunities') { <app-opportunities /> }
              @case ('tasks') { <app-tasks /> }
              @case ('activities') { <app-activities /> }
              @case ('users-roles') { <app-users-roles /> }
              @case ('email-templates') { <app-email-templates /> }
              @case ('audit-log') { <app-audit-log /> }
            }
          </main>
        </div>
      </div>

      <!-- Modals and Slide-overs -->
      @if (uiService.isProfileModalOpen()) { <app-profile-modal /> }
      @if (uiService.selectedCompany() !== undefined) { <app-company-modal /> }
      @if (uiService.selectedContact() !== undefined) { <app-contact-modal /> }
      @if (uiService.selectedOpportunity() !== undefined) { <app-opportunity-modal /> }
      @if (uiService.editingTask() !== undefined) { <app-task-modal /> }
      @if (uiService.editingActivity() !== undefined) { <app-activity-modal /> }
      @if (uiService.autoGeneratedActivity()) { <app-activity-modal [isAutoGenerated]="true" /> }
      @if (uiService.editingUser() !== undefined) { <app-user-modal /> }
      @if (uiService.editingTemplate() !== undefined) { <app-email-template-modal /> }
      @if (uiService.previewingTemplate()) { <app-email-template-preview-modal /> }
      @if (uiService.emailComposerData().to) { <app-email-composer-modal /> }
      @if (uiService.isImportModalOpen()) { <app-import-modal /> }
      @if (uiService.activeColumnCustomization()) { <app-column-customization /> }

    } @else {
      <app-auth></app-auth>
    }
  `,
  imports: [
    CommonModule,
    HeaderComponent,
    SidebarComponent,
    DashboardComponent,
    CompaniesComponent,
    ContactsComponent,
    OpportunitiesComponent,
    TasksComponent,
    ActivitiesComponent,
    UsersRolesComponent,
    EmailTemplatesComponent,
    AuditLogComponent,
    AuthComponent,
    ProfileModalComponent,
    CompanyModalComponent,
    ContactModalComponent,
    OpportunityModalComponent,
    TaskModalComponent,
    ActivityModalComponent,
    UserModalComponent,
    EmailTemplateModalComponent,
    EmailComposerModalComponent,
    ImportModalComponent,
    ColumnCustomizationComponent,
    EmailTemplatePreviewModalComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  authService = inject(AuthService);
  uiService = inject(UiService);
}